variables:
  MAVEN_IMAGE: registry.nexus.devops.sprouts.kr/maven:3.8.6-openjdk-11-slim
  DOCKER_IMAGE: registry.nexus.devops.sprouts.kr/docker:20.10.18
  DOCKER_IN_DOCKER_IMAGE: registry.nexus.devops.sprouts.kr/docker:20.10.18-dind

include:
  - project: "gitlab-library/gitlab-ci"
    ref: 0.0.4
    file:
      - 'template/maven-service-with-version/prepare.gitlab-ci.yml'
      - 'template/maven-service-with-version/build.maven.gitlab-ci.yml'
      - 'template/maven-service-with-version/test.maven.gitlab-ci.yml'
      - 'template/maven-service-with-version/quality.gitlab-ci.yml'
      - 'template/maven-service-with-version/build.docker.gitlab-ci.yml'
      - 'template/maven-service-with-version/deploy.docker.gitlab-ci.yml'
      - 'template/maven-service-with-version/finish.gitlab-ci.yml'

stages:
  - prepare
  - maven-build
  - maven-test
  - quality
  - docker-build
  - docker-deploy
  - finish
