server:
  port: 8080
  servlet:
    context-path: /framework/oauth/resource/api

spring:
  security:
    user:
      password: ${random.uuid}
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin.sprouts.kr/
  cloud:
    discovery:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:sprouts_framework_oauth_resource
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        legacy_limit_handler: true
        jdbc:
          time_zone: Asia/Seoul

eureka:
  instance:
     instance-id: ${random.uuid}
     prefer-ip-address: true
     lease-renewal-interval-in-seconds: 3
     lease-expiration-duration-in-seconds: 10
  client:
    client:
      enabled: false
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    disable-delta: false
    service-url:
      defaultZone: http://discovery.framework.sprouts.kr/eureka/

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  info:
    java:
      enabled: true

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 5
        waitDuration: 1000
    instances:
      default:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        failureRateThreshold: 80
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s
    instances:
      default:
        baseConfig: default

logbook:
  include:
    - ${server.servlet.context-path}/**
  exclude:
    - ${server.servlet.context-path}/actuator/**
    - ${server.servlet.context-path}/h2-console/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  strategy: default
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
    parameters:
      - access_token
  write:
    chunk-size: 4000

logging.level:
  root: WARN
  org.zalando.logbook: TRACE
  kr.sprouts: DEBUG

sprouts:
  logstash-appender:
    name: LOGSTASH
    identifier: ${spring.application.name}-${spring.profiles.active}
    destinations:
      - host: 127.0.0.1
        port: 5045
  web:
    response:
      default-host: gateway
      hosts:
        - name: gateway
          url: http://127.0.0.1:8080${server.servlet.context-path}
  security:
    http:
      permit-all.patterns:
        - /actuator/**
        - /h2-console/**
    credential:
      header:
        name: Authorization
        prefix: Bearer
        codec: BASE64_URL
      consumers:
        - id: 000000fc-1934-42af-90f5-3004cd40257e
          name: AccessTokenConsumer
          type: BEARER_TOKEN
          algorithm: HS512
          codec: BASE64_URL
          encodedSecret: gj9OkDY_BRelaDXsOg2bDOz4EJR7SXvcFCFspCTb4GKdGx7PxVqWidIrY_YtBJsEcndGROc-RUww2twUwTR6Lg==
          validProviders:
            - id: 00000083-3bae-4b13-b033-ebd8e779a1b0
              name: AccessTokenProvider
        - id: ffffff38-5052-433a-a14d-0fe45813b7c5
          name: ApiKeyConsumer
          type: API_KEY
          algorithm: AES256
          codec: BASE64_URL
          encodedSecret: VhIW0Qwfqwm9KGVk6dBfyD0iBlfJSOzCofPdoxUqABg=
          validProviders:
            - id: ffffff32-4858-43c8-b386-8ae748b0e394
              name: ApiKeyProvider
